print("THÔNG TIN HIT 16")
hoten=input(" Nhập họ và tên của cậu : ")
tuoi=int(input("Cậu mấy tuổi rùi nhỉ ? "))
gioitinh=input("Giới tính của cậu (Nam/Nữ) ?")
tinhtranghonnhan=input("Tình trạng hôn nhân của cậu ( Độc thân / Hẹn hò/ Kết hôn/Ly hôn/Khác) :")
print(hoten)
print(tuoi)
print(gioitinh)
print(tinhtranghonnhan)
print("Thông tin đã được in lên terminal của trường.Muốn có người iu vui lòng liên hệ ngay anh Hùng !!!")